services:
  backend:
    build:
      context: .
      dockerfile: deployments/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPOTIFY_ID: ${SPOTIFY_ID}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
