version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPOTIFY_ID: ${SPOTIFY_ID}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
