openapi: 3.0.0
info:
  title: Guess The Song API
  description: API for Guess The Song Spotify Integration
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /v1/spotify/auth:
    get:
      summary: Get Spotify Authorization URL
      description: Returns a URL that users can visit to authorize the application with their Spotify account
      operationId: getSpotifyAuthUrl
      tags:
        - spotify
      responses:
        "200":
          description: Successfully retrieved authorization URL
          content:
            application/json:
              schema:
                $ref: ./schemas/Auth.json
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
