name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  commit-hash:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit hash
        id: get_commit
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

  build-and-push-image:
    needs:
      - commit-hash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployments/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/kazalo11/guess-the-song-backend:latest
            ghcr.io/kazalo11/guess-the-song-backend:${{ github.sha }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployments/web/Dockerfile
          push: true
          tags: |
            ghcr.io/kazalo11/guess-the-song-frontend:latest
            ghcr.io/kazalo11/guess-the-song-frontend:${{ github.sha }}

    env:
      SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
      SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}

  